allowed-origins: http://localhost:4200
default-password: password
spring:
  h2:
    console:
      enabled: false
logging:
        level:
          org:
            springframework:
              security=TRACE:
